### PR TITLE
Extract `install` command [semver:minor]

### LINKED ISSUE #13: `setup` command requires more scopes than necessary
## What happened:

step: `- github-cli/setup`

```
GH CLI installed
/usr/bin/gh

Authenticating GH CLI
github.com
  X github.com: the token in GITHUB_TOKEN is missing required scopes 'repo', 'read:org'
  

Exited with code exit status 1
CircleCI received exit code 1
```

https://app.circleci.com/pipelines/github/pgahq/coach-tools-backend/8091/workflows/8d041e01-362d-4155-9da8-54a0fd74466f/jobs/40666?invite=true#step-103-102

## Expected behavior:

It should be possible to _install_ the github-cli with this orb, without having specific scopes. We only use the github cli to create and report github Deployments. Per the principle of least privelege, we only provide `repo_deployment` scope to our circle contexts. This scope is sufficient to create Deployment records and to set their status accordingly. Unfortunately, this scope is not sufficient for `gh auth status` and so the setup command fails.

## Additional Information:

It is admirable that this orb's `setup` command reports auth status and does some default configuration. However, it should be possible for users to _only_ install the cli, if they so choose. Installation itself does not require _any_ scopes. Our usage is known to work with the `repo_deployment` scope, we just need to install the cli.

### PR DESCRIPTION
**Pull request by jasonkarns**
closes #13 

- Adds `install` command for install-only (without authentication or configuration)
- DRY up the auth/config step in `setup` command to leverage the `install` command
- Renames setup script as `configure.sh` now that it doesn't do installation
- Includes install-only example

### CODE REVIEW

**Comment by jasonkarns** [comment]
I added an explicit assertion in the integration test, but I'm not sure how to trigger the circle workflow. They don't appear to be running on PRs.

**Comment by gmemstr** [comment]
@jasonkarns Due to how orb tests work, we have to manually trigger them - I'm doing so now :)

**Comment by KyleTryon** [comment]
@jasonkarns Thank you for the contribution! I had not known of any use-cases at the time of creation that would work under different scopes, thank you for sharing this and resolving the issue.
The error reported here should be something operational due to a security concern, attempting to resolve it now.

**Comment by jasonkarns** [comment]
@KyleTryon i appreciate it! you'll notice that I also opened a feature request against the github cli itself that would (hopefully) allow one to invoke `gh auth status` with reduced scopes. https://github.com/cli/cli/issues/4827

If you have thoughts on how that hypothetical feature should work (as it relates to CI usage), I would welcome your input on that issue.

**Comment by motionsuggests** [comment]
@jasonkarns This is great! It will make implementing https://github.com/CircleCI-Public/github-cli-orb/issues/9 much easier.

**Comment by motionsuggests** [comment]
Any word on this?

**Comment by KyleTryon** [comment]
Apologies @motionsuggests, many orbs to get to. Taking a look at this now/today

**Comment by KyleTryon** [comment]
Apologies again. Just got the build error resolved and all of the tests have passed. Thank you @jasonkarns Pushing this now!

**Review by KyleTryon — APPROVED** [review]

**Pull request merged**
