### PR TITLE
feat!: add hostname parameter [semver:major]

### PR DESCRIPTION
**Pull request by KyleTryon**
* Update to GH CLI version 2.3.0 by default.
* Add `--hostname` parameter for GH Enterprise support
* Improved integration testing

### CODE REVIEW

**Comment by KyleTryon** [comment]
@motionsuggests Have a PR ready here I'd love if you could comment on. I do not have an enterprise instance to play with. We have the hostname set here, it did require that we use version 2.3 of the CLI to gain access to the `gh auth git-setup` command. 

What I'm concerned with here is the credential helper, I assume we might want to update the URL [here ](https://github.com/CircleCI-Public/github-cli-orb/pull/19/files#diff-d61ce516e455311297d0de439f4d64254b50775a334a2d33332a6693517bbc93R10)to use the `--hostname` provided host. Would you happen to know?

**Comment by motionsuggests** [comment]
Thanks @KyleTryon I'll take a look today. I might be able to test it in enterprise, I'll let you know.

**Comment by motionsuggests** [comment]
I looked it over and I'm unsure about the credential helper. See this issue I opened on gh-cli https://github.com/cli/cli/issues/4740. It seems like we don't need the credential helper at all. Setting env vars for token and hostname then just running a command should work.

I was thinking the flow would be 
- install step
- release step with hostname and token as env vars.

**Comment by KyleTryon** [comment]
Indeed credential helper is no longer required with the newer GH CLI. Thank you for all the help @motionsuggests. I would say we are in a significantly more stable place now.

**Comment by motionsuggests** [comment]
🙌  🎉

**Pull request merged**
