### PR TITLE
fix: set gh_enterprise_token when using self-hosted ghes

### PR DESCRIPTION
**Pull request by juburr**
This orb has always worked fine for me on github.com, but errors out for me on a self-hosted GitHub Enterprise Server with the error message below.

```bash
Authenticating GH CLI
You are not logged into the GitHub host "gh.your-organization-here.dev". Run gh auth login -h gh.your-organization-here.dev to authenticate or provide `--force`

Exited with code exit status 1
```

When using GHES, if you place your token in the `GITHUB_TOKEN` environment variable, notice that `gh auth status` will try to use your token to authenticate against github.com, even with `GH_HOST` set and/or an explicit call to `gh auth login`. The tool associates `GITHUB_TOKEN` as belonging to github.com, and instead wants you to use `GH_ENTERPRISE_TOKEN`. If you set `GH_ENTERPRISE_TOKEN` and then unset `GITHUB_TOKEN`, notice that `gh auth status` will no longer show a failed login attempt to github.com.

### CODE REVIEW

**Review by david-montano-circleci — APPROVED** [review]

**Comment by juburr** [comment]
Hold off on merging just yet. I see that `gh auth login` has a required scope of `read:org`. The documentation actually outlines three required scopes: https://cli.github.com/manual/gh_auth_login. I'd like to see if that represents an increase over what's currently required by this orb. i.e., if this would constitute a breaking change for others using tokens with minimal scopes assigned. If so, maybe we could add a boolean login parameter that defaults to false? TBD after additional testing.

**Comment by juburr** [comment]
I made some progress on this. A few things to note:

I don't think we need or want `gh auth login` here. It's not needed to run most `gh` commands.

The root cause to my problem is that orb sets `GITHUB_TOKEN` in the .bashrc file, but the `gh` tool uses `GH_ENTERPRISE_TOKEN` when using GHES instead. If you set `GH_ENTERPRISE_TOKEN` and `GH_HOST` correctly, everything magically works again.

However, if you just do `export GH_ENTERPRISE_TOKEN=$GITHUB_TOKEN`, and then make a call to `gh auth status` (just like this orb's `gh/setup` command), notice it exits with status code 1 (this orb has an `||` statement that masks this failure, so you may not notice unless you try locally).

The main issue is that because this orb blindly places `GITHUB_TOKEN` into the .bashrc file, it results in the `gh` tool unexpectedly reaching out to github.com in addition GHES. Notice that for some unknown reason `github.com` is listed in the `gh auth status` results, which is the reason why it's throwing an error. The solution for me was to just `unset GITHUB_TOKEN`. It prevents `gh` tool from reaching out to github.com.

So maybe the solution looks something like this?
```bash
if [[ "${PARAM_GH_HOSTNAME}" == "github.com" ]]; then
  export GITHUB_TOKEN=${!PARAM_GH_TOKEN}
  echo "export GITHUB_TOKEN=\"${GITHUB_TOKEN}\"" >>"$BASH_ENV"
else
  export GH_ENTERPRISE_TOKEN=${!PARAM_GH_TOKEN}
  export GH_HOST=${PARAM_GH_HOSTNAME}
  echo "export GH_HOST=github.accenturefederaldev.com" >> "$BASH_ENV"
  echo "export GH_ENTERPRISE_TOKEN=$GITHUB_TOKEN" >> "$BASH_ENV"
fi
```

Only problem is `GITHUB_TOKEN` can still be present for some people if that's what it's called in their context. Will circle back to this when I find time & maybe make a new commit...

**Comment by juburr** [comment]
Updated to remove `gh auth login` in favor of `GH_ENTERPRISE_TOKEN`. Confirmed working on both GHES and github.com.

**Comment by juburr** [comment]
Great, thank you! The `gh` CLI tool authors stated that for CI systems the `GH_ENTERPRISE_TOKEN` method is preferred over `gh auth login`: https://github.com/cli/cli/issues/4740#issuecomment-971847009

**Review by david-montano-circleci — APPROVED** [review]

**Pull request merged**
